### PR TITLE
Fix Readme for rake task

### PR DESCRIPTION
**Pull request by anjali-sharma**

### CODE REVIEW

**Comment by jmettraux** [comment]
I'm sorry, this breaks incoming links. I cannot accept the pull request. Many thanks anyway.

**Comment by anjali-sharma** [comment]
no problem.

**Comment by jmettraux** [comment]
Yes, a PR with just https://github.com/jmettraux/rufus-scheduler/pull/206/commits/8cff7b308340cef5f1c440429403d9d19b555536 would be great.

Thanks in advance!

**Comment by anjali-sharma** [comment]
https://github.com/jmettraux/rufus-scheduler/pull/207

**Pull request closed without merging**
