### PR TITLE
removed male-gendered language

### PR DESCRIPTION
**Pull request by suisea**
hi, i'm a nonbinary engineer, and having gendered language at all, *especially* "Sir," in a readme like this is incredibly off-putting and reinforces the idea that most programmers are men. gendered language isn't necessary, even if you're just trying to be playful to the reader. this is just a suggestion. thank you!

### CODE REVIEW

**Comment by jmettraux** [comment]
circular https://twitter.com/swayandsea/status/653593341939027968

**Comment by suisea** [comment]
hehe, hope you know i was calling myself insufferable, not you! ;)

**Comment by jmettraux** [comment]
No, how could I know?

I thought you were referring to occurrences of gendered language in technical documentation.

Have a nice evening!

**Comment by suisea** [comment]
that, too, but mainly i was talking about myself. ;)

**Pull request merged**
