### PR TITLE
Add Puma plugin

### PR DESCRIPTION
**Pull request by javierav**
This PR add a first approach to implements a Puma plugin for run Rufus Scheduler in background.

### configure puma

```ruby
# config/puma.rb

plugin :rufus_scheduler
```

### create scheduler config

```ruby
# config/scheduler.rb

scheduler = Rufus::Scheduler.new

scheduler.every "5s" do
  puts "Every 5 seconds #{Time.current}"
end

scheduler.join
```

### run puma

```
$ bin/rails server

=> Booting Puma
=> Rails 7.1.3.2 application starting in development
...

Every 5 seconds 2024-04-17 14:13:11 UTC
Every 5 seconds 2024-04-17 14:13:16 UTC
Every 5 seconds 2024-04-17 14:13:21 UTC
```

### change scheduler path

```
$ RUFUS_SCHEDULER_PATH="config/my_scheduler.rb" bin/rails server
```

### CODE REVIEW

**Comment by jmettraux** [comment]
Thanks for the detailed pull request.

I do not accept it as it introduces a dependency to Puma which is orthogonal to rufus-scheduler.

May I suggest writing a blog post? A link to it can then be added to rufus-scheduler's readme so that your recipe lives on.

Best regards.

**Comment by javierav** [comment]
Hi @jmettraux 

I understand your reasons for rejecting it, but it doesn't really introduce a dependency on Puma since the file `lib/puma/plugin/rufus_scheduler.rb` is only loaded if the plugin is activated from Puma, if you use the library normally, nothing changes.

However, I will work on the post you say and put it here.

Best regards.

**Comment by javierav** [comment]
Finally I extract this to a new gem: https://github.com/javierav/puma-rufus-scheduler

**Comment by jmettraux** [comment]
> Finally I extract this to a new gem

Well done! Starred!

**Pull request closed without merging**
